apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: kyma-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kyma-events
spec:
  gateways:
    - module-manager-kyma-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            regex: \/v.*\/manifest\/event
      route:
        - destination:
            host: module-manager-event-service
            port:
              number: 2022
---
##### module manager needs a different label than kyma operator to have a sufficient selector in place
apiVersion: v1
kind: Service
metadata:
  name: event-service
spec:
  selector:
    control-plane: controller-manager
  ports:
    - protocol: TCP
      port: 2022
      targetPort: 2022
---
