apiVersion: component.kyma-project.io/v1alpha1
kind: Manifest
metadata:
  labels:
    operator.kyma-project.io/channel: stable
    operator.kyma-project.io/controller-name: manifest
    operator.kyma-project.io/kyma-name: kyma-sample
  name: manifestkyma-sample
  namespace: default
spec:
  resource:
    kind: ConfigMap
    resource: configMaps
    apiVersion: v1
    data: generated_from_manifest
    metadata:
      name: config.map.manifest
  config:
    ref: sha256:36e6fab01f4892c516f088d7d52680d243aaeed415c27bdf9e521184e66ad2df
    name: kyma-project.io/module/example
    repo: k3d-registry.localhost:52445/signed/component-descriptors
    type: oci-ref
  installs:
    - source:
        name: your-own-chart
        repo: k3d-registry.localhost:52445/signed/component-descriptors
        ref: sha256:600989483c323dac3ddec5c636c76e23714bedac3192cb1d7ee4b99c06db708b
        type: oci-ref
      name: nginx-ingress
    - source:
        chartName: nginx-ingress
        url: https://helm.nginx.com/stable
        type: helm-chart
      name: nginx-stable
