apiVersion: component.kyma-project.io/v1alpha1
kind: Manifest
metadata:
  labels:
    operator.kyma-project.io/channel: stable
    operator.kyma-project.io/controller-name: manifest
    operator.kyma-project.io/kyma-name: kyma-sample
  name: manifestkyma-sample
  namespace: default
spec:
  crds:
    ref: sha256:58d0d837393f2e4db3b6febf26fa721479f03ccd36d5969998025a15c4a25a0d
    name: kyma-project.io/module/example
    repo: k3d-registry.localhost:52445/signed/component-descriptors
    type: oci-ref
  resource:
    kind: Kyma
    resource: kymas
    apiVersion: operator.kyma-project.io/v1alpha1
    metadata:
      name: kyma.from.manifest
      namespace: default
    spec:
      profile: production
      channel: stable
  config:
    ref: sha256:c9f7103442b88057edc02bc90e101e93b43c79a6137aa1b2cfb3b44f1a8f3255
    name: kyma-project.io/module/example
    repo: k3d-registry.localhost:52445/signed/component-descriptors
    type: oci-ref
  installs:
    - source:
        name: kyma-project.io/module/example
        repo: k3d-registry.localhost:52445/signed/component-descriptors
        ref: sha256:600989483c323dac3ddec5c636c76e23714bedac3192cb1d7ee4b99c06db708b
        type: oci-ref
      name: nginx-ingress
    - source:
        chartName: mysql
        url: https://charts.bitnami.com/bitnami
        type: helm-chart
      name: bitnami
